spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gpt-database?useUnicode=true&characterEncoding=utf-8
    username: root
    password: nn123456

server:
  port: 9999

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.reshumbrella.entity
